---
arch_packages:
  # terminal ++ cli tools
  - alacritty
  - bat
  - bottom
  - exa
  - fd
  - fzf
  - htop
  - lazygit
  - neofetch
  - ripgrep
  - rsync
  - stow
  - tectonic
  - udisks2
  - vim
  - zoxide

  # shell
  - ttf-hack-nerd
  - starship
  - zsh

  # system
  - base
  - linux
  - linux-firmware
  - man
  - man-db
  - man-pages
  - texinfo
  - btrfs-progs
  - grub
  - efibootmgr
  - os-prober
  - networkmanager
  - networkmanager-fortisslvpn
  - network-manager-applet
  - pipewire
  - pipewire-audio
  - pipewire-alsa
  - pipewire-pulse
  - wireplumber

aur_packages:
  - erdtree
