---
- name: Install Arch repo packages
  ansible.builtin.pacman:
    name: "{{ item }}"
    state: present
  loop: "{{ arch_packages }}"

- name: Install AUR packages
  become: true
  become_user: kain
  kewlfft.aur.aur:
    name: "{{ item }}"
  loop: "{{ aur_packages }}"

- name: Make sure these are not installed
  ansible.builtin.pacman:
    name: "{{ item }}"
    state: absent
  loop: "{{ not_installed_arch }}"

- name: Write electron-flags.conf
  become_user: tommy
  ansible.builtin.copy:
    content: "{{ electron_flags }}"
    dest: /home/tommy/.config/electron-flags.conf

- name: Write electron13-flags.conf
  become_user: tommy
  ansible.builtin.copy:
    content: "{{ electron13_flags }}"
    dest: /home/tommy/.config/electron13-flags.conf
