---
- name: Install fprintd packages
  ansible.builtin.package:
    name:
      - fprintd
    state: present

- name: Setup fprintd service file
  ansible.builtin.blockinfile:
    path: /usr/lib/systemd/system/fprintd.service
    block: |
      [Install]
      WantedBy=multi-user.target
  register: fprintd_service_file

- name: Restart fprintd.service
  ansible.builtin.service:
    name: fprintd
    enabled: true
    state: started
  when: fprintd_service_file is changed

- name: Inform about next steps
  ansible.builtin.debug:
    msg: Run the remaining steps in the Fedora37 Framework guide regarding fprintd if you have not yet!
