---
- name: Ensure git repos
  become_user: tommy
  ansible.builtin.git:
    repo: "{{ git_repo }}"
    dest: "{{ repo_dest }}"

- name: Copy RP-Dvorak to X11 symbols
  ansible.builtin.copy:
    src: "{{ repo_dest }}/ubuntu/real-prog-dvorak"
    dest: /usr/share/kbd/keymaps/real-prog-dvorak
