session: capturedlambda
root: ~/coding/capturedlambda/
windows:
  - name: dev
    layout: main-vertical
    commands:
      - nvim
    panes:
      - commands:
          - clear
      - commands:
          - clear
  - name: sh
    layout: main-vertical
    commands:
      - clear
    panes:
      - commands:
          - clear
      - commands:
          - clear
