session: capturedlambda
root: ~/coding/capturedlambda/
windows:
  - name: dev
    layout: main-horizontal
    commands:
      - nvim
    panes:
      - commands:
          - npm run dev
  - name: sh
    commands:
      - clear
