session: capturedlambda
root: ~/coding/capturedlambda/
windows:
  - name: dev
    layout: main-horizontal
    commands:
      - nvim
  - name: server
    layout: main-horizontal
    commands:
      - npm run dev
