session: corries
root: ~/coding/corries/
windows:
  - name: dev
    layout: main-horizontal
    commands:
      - nvim
    panes:
      - commands:
          - clear
  - name: git
    layout: main-horizontal
    commands:
      - lazygit
