session: planning_api_core_adapter
root: ~/work/Planning/lib/planning_api_core_adapter/
windows:
  - name: dev
    layout: main-vertical
    commands:
      - nvim
    panes:
      - commands:
          - clear
      - commands:
          - clear
  - name: sh
    layout: main-vertical
    commands:
      - clear
    panes:
      - commands:
          - clear
      - commands:
          - clear
