session: planning_core
root: ~/work/Planning
windows:
  - name: core
    root: lib/planning_core_rust/
    layout: main-vertical
    commands:
      - conda activate planning_api
      - nvim
    panes:
      - commands:
          - bacon
      - commands:
          - pushd ~/work/Planning/projects/planning_api/
          - conda activate planning_api
          - poetry shell
          - poetry install
          - popd
          - maturin develop --release
          - redis-cli FLUSHALL
          - AWS_DEFAULT_REGION=foo python3 ../../projects/planning_api/src/planning_api/fast_api_app/main.py
  - name: api
    root: projects/planning_api
    layout: main-vertical
    commands:
      - conda activate planning_api
      - nvim
    panes:
      - commands:
          - conda activate planning_api
  - name: sh
    layout: main-vertical
    commands:
      - conda activate planning_api
    panes:
      - commands:
          - conda activate planning_api
  - name: server
    root: .
    layout: even-vertical
    commands:
      - killall redis-server
      - sleep 2
      - redis-server
    panes:
      - root: projects/planning_api
        commands:
          - conda activate planning_api
