session: planning_scenarios
root: ~/work/Planning/lib/planning_scenarios/
windows:
  - name: dev
    layout: main-vertical
    commands:
      - conda activate planning_scenarios
      - nvim
    panes:
      - commands:
          - conda activate planning_scenarios
          - clear
      - commands:
          - conda activate planning_scenarios
          - clear
  - name: sh
    layout: main-vertical
    commands:
      - conda activate planning_scenarios
      - clear
    panes:
      - commands:
          - conda activate planning_scenarios
          - clear
      - commands:
          - conda activate planning_scenarios
          - clear
