session: planning
root: ~/work/planning
windows:
  - name: core
    root: .
    layout: main-horizontal
    commands:
      - nvim
    panes:
      - root: lib/planning_core_rust/
        commands:
          - clear
  - name: git
    commands:
      - lazygit
  - name: moco
    root: ../MocoTrackingClient/
    commands:
      - poetry run python moco_client.py
