session: planning
root: ~/work/planning
windows:
  - name: core
    root: .
    layout: main-horizontal
    commands:
      - poetry shell -C projects/planning_api
      - nvim
  - name: sh
    layout: main-horizontal
    commands:
      - poetry shell -C projects/planning_api
  - name: moco
    layout: main-horizontal
    root: ../MocoTrackingClient/
    commands:
      - git pull
      - poetry run python moco_client.py
