session: planning_core
root: ~/work/planning
windows:
  - name: core
    root: .
    layout: main-vertical
    commands:
      - nvim
    panes:
      - root: lib/planning_core_rust/
        commands:
          - bacon
      - root: .
        commands:
          - clear
  - name: sh
    layout: main-vertical
    commands:
      - clear
    panes:
      - commands:
          - clear
  - name: moco
    root: ../MocoTrackingClient/
    commands:
      - poetry run python moco_client.py
