session: tdos
root: ~/coding/tdos/
windows:
  - name: dev
    layout: main-horizontal
    commands:
      - nvim
    panes:
      - commands:
          - clear
  - name: sh
    layout: main-horizontal
    commands:
      - clear
