---
arch_packages:
  # desktop
  - dunst
  - kanshi
  - light
  - playerctl
  - polkit-kde-agent
  - swayidle
  # - swaylock
  - wdisplays
  - wl-clipboard
  - wlr-randr
  - wlsunset
  - wofi
  - xdg-desktop-portal
  # - xdg-desktop-portal-wlr
  - xorg-xwayland

  # appearance
  - qt5ct
  - qt6ct
  - qt5-wayland
  - qt6-wayland
  - lxappearance
  - nwg-look

  # screenshots
  - grim
  - slurp
  - swappy

  # gui
  - discord
  - imv
  - telegram-desktop
  - thunderbird
  - vlc

aur_packages:
  # - sddm-git
  # - archlinux-themes-sddm
  - brave-bin
  - megasync-bin
  - zoom
  - eww-wayland
  - hyprland
  - hyprpaper-git
  - swaylock-effects
  - waybar-hyprland-git
  - xdg-desktop-portal-hyprland-git
  - tofi
  - wlogout

electon_flags: |
  --ozone-platform-hint=auto
  --enable-webrtc-pipewire-capturer
  --gtk-version=4

electon13_flags: |
  --enable-features=UseOzonePlatform
  --ozone-platform=wayland
