---
arch_packages:
  # desktop
  - hyprland
  - hyprpaper
  - dunst
  - kanshi
  - light
  - playerctl
  - polkit-kde-agent
  - swayidle
  - wl-clipboard
  - wofi
  - xdg-desktop-portal
  - xorg-xwayland

  # appearance
  - qt5ct
  - qt6ct
  - qt5-wayland
  - qt6-wayland
  - lxappearance

  # screenshots
  - grim
  - slurp
  - swappy

  # gui
  - discord
  - imv
  - telegram-desktop
  - thunderbird
  - vlc
  - zathura
  - zathura-cb
  - zathura-djvu
  - zathura-pdf-mupdf
  - zathura-ps

aur_packages:
  # - sddm-git
  # - archlinux-themes-sddm
  - brave-bin
  - megasync-bin
  - zoom
  - eww-wayland
  - swaylock-effects
  - waybar-hyprland-git
  - xdg-desktop-portal-hyprland-git
  - nwg-look
  - tofi
  - wdisplays
  - wlogout
  - wlsunset

electon_flags: |
  --ozone-platform-hint=auto
  --enable-webrtc-pipewire-capturer
  --gtk-version=4

electon13_flags: |
  --enable-features=UseOzonePlatform
  --ozone-platform=wayland
