---
arch_packages:
  ### compilers ++ build tools
  - gcc
  - gcc-fortran
  - clang
  - cmake
  - meson
  - ninja
  - rustup
  - nodejs

  ### LSPs / Linters
  # c/c++/fortran
  - cppcheck

  # lua
  - stylua
  - luacheck

  # python
  - python-black
  - ruff

  # shell/docker/config files/etc
  - shellcheck
  - ansible-lint

  ### libs
  - python-matplotlib
  - python-numpy
  - python-pandas
  - openmp
  - openblas

  ### misc
  - doxygen
  - jupyterlab
  - just
  - vim

aur_packages:
  - hadolint-bin
  - prettierd
  - neovim-nightly
  - python-polars-bin
