---
arch_packages:
  ### compilers ++ build tools
  - gcc
  - gcc-fortran
  - clang
  - cmake
  - meson
  - ninja
  - rustup
  - nodejs
  - zig

  ### LSPs / Linters
  - cppcheck
  - ccls
  - stylua
  - luacheck
  - python-black
  - ruff # python linter
  - shellcheck
  - ansible-lint
  - zls

  ### libs
  - python-matplotlib
  - python-numpy
  - python-pandas
  - openmp
  - openblas

  ### misc
  - doxygen
  - jupyterlab
  - just
  - vim

aur_packages:
  - hadolint-bin
  - prettierd
  - neovim-nightly
  - python-polars-bin
