[rocks]

[plugins]
"rocks.nvim" = "2.27.0"
"rocks-config.nvim" = "1.5.0"
"rocks-git.nvim" = "1.5.0"

nvim-treesitter = "scm"
nvim-treesitter-context = "scm"
tree-sitter-just = { git = "indianboy42/tree-sitter-just" }
tree-sitter-bash = "scm"
tree-sitter-vim = "scm"
tree-sitter-vimdoc = "scm"
tree-sitter-lua = "scm"
tree-sitter-markdown = "scm"
tree-sitter-python = "scm"
tree-sitter-c = "scm"
tree-sitter-cpp = "scm"
tree-sitter-rust = "scm"
tree-sitter-go = "scm"
tree-sitter-zig = "scm"
tree-sitter-astro = "scm"
tree-sitter-html = "scm"
tree-sitter-json = "scm"
tree-sitter-javascript = "scm"
tree-sitter-typescript = "scm"
tree-sitter-css = "scm"
tree-sitter-scss = "scm"
tree-sitter-yaml = "scm"
tree-sitter-toml = "scm"
tree-sitter-hyprlang = "scm"

gruvbox-material = { git = "sainnhe/gruvbox-material" }
"heirline.nvim" = "1.0.3"
"heirline-components.nvim" = { git = "Zeioth/heirline-components.nvim" }
nvim-web-devicons = "0.100"

"which-key.nvim" = { git = "folke/which-key.nvim" }

"vim-fugitive" = { git = "tpope/vim-fugitive" }
"gitsigns.nvim" = { git = "lewis6991/gitsigns.nvim" }

neorg = "8.4.0"
"telescope.nvim" = "scm"
"telescope-undo.nvim" = "scm"
"telescope-zf-native.nvim" = { git = "natecraddock/telescope-zf-native.nvim" }
"leap.nvim" = { git = "ggandor/leap.nvim" }
"harpoon" = { git = "ThePrimeagen/harpoon", branch = "harpoon2" }
"oil.nvim" = "2.8.0"
"tmux.nvim" = "scm"
