[rocks]

[plugins]
"rocks.nvim" = "2.28.0"
"rocks-config.nvim" = "1.5.0"
"rocks-git.nvim" = "1.5.0"

nvim-treesitter = { git = "nvim-treesitter/nvim-treesitter" }
nvim-treesitter-context = { git = "nvim-treesitter/nvim-treesitter-context" }

gruvbox-material = { git = "sainnhe/gruvbox-material" }
"heirline.nvim" = "1.0.3"
"heirline-components.nvim" = { git = "Zeioth/heirline-components.nvim" }
nvim-web-devicons = "0.100"

"which-key.nvim" = { git = "folke/which-key.nvim" }

"vim-fugitive" = { git = "tpope/vim-fugitive" }
"gitsigns.nvim" = { git = "lewis6991/gitsigns.nvim" }

neorg = "8.4.0"
"telescope.nvim" = "scm"
"telescope-undo.nvim" = "scm"
"telescope-zf-native.nvim" = { git = "natecraddock/telescope-zf-native.nvim" }
"leap.nvim" = { git = "ggandor/leap.nvim" }
"harpoon" = { git = "ThePrimeagen/harpoon", branch = "harpoon2" }
"oil.nvim" = "2.9.0"
"tmux.nvim" = "scm"

"mason.nvim" = "1.10.0"
"mason-tool-installer.nvim" = "scm"
"formatter.nvim" = "scm"
nvim-lint = "scm"

nvim-lspconfig = "0.1.7"
nvim-cmp = { git = "hrsh7th/nvim-cmp" }
cmp-path = "scm"
cmp-nvim-lsp = "scm"
cmp-buffer = "scm"
cmp-cmdline = "scm"
"lspkind.nvim" = "scm"
rustaceanvim = "4.23.2"
"otter.nvim" = "1.15.0"
"trouble.nvim" = "2.10.0"

nvim-dap = "0.7.0"
nvim-dap-ui = "4.0.0"
nvim-dap-python = "scm"
nvim-dap-virtual-text = "scm"
