#!/usr/bin/env zsh

function gco() {
    my_branch=$(git branch -a --no-color | sort | uniq | tr -d " " | fzf --select-1 --ansi --preview 'git log --graph --color=always --format="%C(auto)%h%d %s %C(black)%C(bold)%cr" {} 2>/dev/null')
    if echo $my_branch | grep -q "remotes/origin"; then
        my_branch=${my_branch##remotes/origin/}
    fi
    if echo "$my_branch" | grep -q -P --regexp='\*'; then
        my_branch=${my_branch##\*}
    fi

    git checkout $my_branch
}

alias g="git"
alias gg="git status -s"
alias ggg="git status"
alias gd="git diff"
alias gs="git checkout"
alias ga="git add"
alias gA="git add -A"
alias gc="git commit"
alias gcA="git add -A && git commit"
alias gcaa="git add -A && git commit"
alias gca="git commit --amend --no-edit"
alias gC="git add -A && git commit --amend --no-edit"
alias gB="git checkout -b"
alias gp="git pull"
alias gP="git push origin"
alias gPF="git push --force-with-lease"
alias gPU="git push --set-upstream"
alias lg="lazygit"
alias v="nvim"
alias ls="eza --icons=always"
alias la="eza -aa"
alias ll="eza -l"
alias lla="eza -la"
alias lt="eza --tree"
alias cp="cp -i"
alias rm="rm -i"
alias mv="mv -i"
alias mkdir="mkdir -p"
alias jf="just --chooser \"fzf --layout=reverse --height=40\" --choose"
alias m="make"
alias mw="make -C $HOME/work"

alias rip_nvim="rip ~/.local/share/nvim ~/.local/state/nvim ~/.cache/nvim ~/dots/nvim/lazy-lock.json"
