---
- name: Install stow
  ansible.builtin.pacman:
    name: stow
    state: present

- name: Enable fstrim.service
  ansible.builtin.service:
    name: fstrim.service
    state: started

- name: Stow dotfiles
  become_user: tommy
  ansible.builtin.shell:
    cmd: "stow -d $HOME/dots/config -t ~/ {{ item }}"
  loop: "{{ common_stows }}"

- name: Stow scripts
  become_user: tommy
  ansible.builtin.shell:
    cmd: "stow -d $HOME/dots -t ~/ scripts"
