#!/usr/bin/env bash
set -euo pipefail

readonly COLOR_RESET="\033[0m"
readonly BRIGHT_RED="\033[1;31m"
readonly BRIGHT_GREEN="\033[1;32m"
readonly BRIGHT_YELLOW="\033[1;33m"
readonly BRIGHT_BLUE="\033[1;34m"
# readonly IFS=' '
SCRIPT_PATH=$(realpath "$0")
SCRIPT_DIR=$(dirname "$SCRIPT_PATH")

SUCCESS=0
SUCCESS_SKIP=1
SUCCESS_WARN=2
FAIL=3

cmd_code=$SUCCESS
cmd_msg=""
cmd_location=""

${SCRIPT_DIR}/refresh_env

echo "$SCRIPT_DIR"

# shellcheck source=/dev/null
source "${SCRIPT_DIR}/.env"

# shellcheck source=apt
source "${SCRIPT_DIR}/apt"

# shellcheck source=arch
source "${SCRIPT_DIR}/arch"

pushd() {
    command pushd "$@" >/dev/null
}

popd() {
    command popd >/dev/null
}
__log() {
    name="$1"
    state="$2"
    color="$3"
    msg="$4"
    echo -e "${color}[ dm:${name} ] ${state} |${COLOR_RESET} ${msg}"
}

__info() {
    if [ $# -gt 0 ]; then
        name="$1"
        msg="$2"
    else
        name="$cmd_location"
        msg="$cmd_msg"
    fi
    __log "$name" "INFO" "$BRIGHT_BLUE" "$msg"
}

__warn() {
    # if [ $# -gt 0 ]; then
    #     name="$1"
    #     msg="$2"
    # else
    #     name="$cmd_location"
    #     msg="$cmd_msg"
    # fi
    name="$cmd_location"
    msg="$cmd_msg"
    __log "$name" "WARN" "$BRIGHT_YELLOW" "$msg"
}

__fail() {
    # if [ $# -gt 0 ]; then
    #     name="$1"
    #     msg="$2"
    # else
    #     name="$cmd_location"
    #     msg="$cmd_msg"
    # fi
    name="$cmd_location"
    msg="$cmd_msg"
    __log "$name" "FAIL" "$BRIGHT_RED" "$msg"
}

__success() {
    if [ $# -gt 0 ]; then
        name="$1"
        msg="$2"
    else
        name="$cmd_location"
        msg="$cmd_msg"
    fi
    __log "$name" "SUCCESS" "$BRIGHT_GREEN" "$msg"
}

__handle_err() {
    case "$cmd_code" in
    "$SUCCESS_SKIP") __success ;;
    "$SUCCESS_WARN") __warn ;;
    "$FAIL")
        __fail
        exit "$cmd_code"
        ;;
    esac

    cmd_code=$SUCCESS
    cmd_msg=""
    cmd_location=""
}

dm_pkgs() {
    name="pkgs"
    __info "$name" "starting"
    case "$_HOST" in
    "darwin")
        prep_pkgs "brew"
        brew bundle --cleanup --file "${SCRIPT_DIR}/Brewfile" install

        if git status --porcelain | grep "Brewfile.lock.json"; then
            git add dm/Brewfile.lock.json
            git commit -m "update Brewfile.lock"
        fi
        ;;

    "vorador")
        prep_pkgs "apt"
        apt_install=$(tr '\n' ' ' <"$HOME/dots/state/apt_install")
        apt_remove=$(tr '\n' ' ' <"$HOME/dots/state/apt_remove")
        sudo apt remove "$apt_remove"
        sudo apt autoremove
        sudo apt update
        sudo apt upgrade
        sudo apt install "$apt_install"
        mv "$HOME/dots/state/apt_want" "$HOME/dots/state/apt_current"
        rm "$HOME"/dots/state/apt_{install,remove}
        ;;

    "moebius" | "audron")
        prep_pkgs "pacman"
        pacman_install="$HOME/dots/state/pacman_install"
        pacman_remove="$HOME/dots/state/pacman_remove"
        prep_pkgs "aur"
        aur_install="$HOME/dots/state/aur_install"
        aur_remove="$HOME/dots/state/aur_remove"

        if [ -s "$pacman_remove" ]; then
            sudo pacman -R $(awk '{print $1}' $pacman_remove)
        else
            __info "$name" "pacman has nothing to remove"
        fi

        sudo pacman -Syu

        if [ -s "$pacman_install" ]; then
            sudo pacman --needed -S $(awk '{print $1}' $pacman_install)
        else
            __info "$name" "pacman has nothing to install"
        fi

        if [ -s "$aur_remove" ]; then
            paru --aur -R $(awk '{print $1}' $aur_remove)
        else
            __info "$name" "aur helper has nothing to remove"
        fi

        paru --aur -Syu

        if [ -s "$aur_install" ]; then
            paru --aur --needed -S $(awk '{print $1}' $aur_install)
        else
            __info "$name" "aur helper has nothing to install"
        fi

        mv "$HOME/dots/state/pacman_want" "$HOME/dots/state/pacman_current"
        rm "$HOME"/dots/state/pacman_{install,remove}
        mv "$HOME/dots/state/aur_want" "$HOME/dots/state/aur_current"
        rm "$HOME"/dots/state/aur_{install,remove}
        ;;
    esac
    if command -v rustup &>/dev/null; then
        rustup update
    fi
    __success "$name" "finished"
}

prep_pkgs() {
    pkg_manager="$1"
    state_dir="$HOME/dots/state"
    current_state="${state_dir}/${1}_current"
    want="${state_dir}/${1}_want"
    install="${state_dir}/${1}_install"
    remove="${state_dir}/${1}_remove"

    truncate -s0 "$want"
    truncate -s0 "$install"
    truncate -s0 "$remove"

    touch "$current_state"
    touch "$want"
    touch "$install"
    touch "$remove"

    if [[ "$pkg_manager" == "apt" ]]; then
        pkgs=("${APT[@]}")
    elif [[ "$pkg_manager" == "pacman" ]]; then
        pkgs=("${PACMAN[@]}")
    elif [[ "$pkg_manager" == "aur" ]]; then
        pkgs=("${AUR[@]}")
    fi

    IFS=$'\n' pkgs=($(sort --unique <<<"${pkgs[*]}"))

    for p in "${pkgs[@]}"; do
        echo "$p" >>"$want"
    done

    comm -23 "$want" "$current_state" >"$install"
    comm -13 "$want" "$current_state" >"$remove"
}

dm_sync() {
    __info "sync" "starting"

    IFS=' ' read -ra __commands <<<"$VALID_COMMANDS"
    for c in "${__commands[@]}"; do
        [[ $c == "sync" ]] && continue
        eval "dm_${c}"
        __handle_err
    done

    __success "sync" "finished"
}

__main() {
    pushd ~/dots
    git pull || true
    popd
    for c in "${COMMANDS[@]}"; do
        if [[ ! "$VALID_COMMANDS" =~ [[:space:]]$c[[:space:]] ]]; then
            cmd_code=$FAIL
            cmd_location="main"
            cmd_msg="$c is not a valid dm command; valid commands:$VALID_COMMANDS"
        fi
    done
    __handle_err
    mkdir -p ~/.config ~/.local/bin ~/dots/state
    for c in "${COMMANDS[@]}"; do
        eval "dm_${c}"
        __handle_err
    done
    __handle_err
}

COMMANDS=()
VALID_COMMANDS=" pkgs sync "
if [ $# -gt 0 ]; then
    read -ra COMMANDS <<<"$@"
else
    COMMANDS=("sync")
fi

IFS=' ' read -ra ROLES <<<"$ROLES"
IFS=' ' read -ra REPOS <<<"$REPOS"
__main
