#!/usr/bin/env bash

SCRIPT_PATH=$(realpath "$0")
SCRIPT_DIR=$(dirname "$SCRIPT_PATH")

UNAME_S="$(uname -s)"
_HOST=""
ALLOWED_HOSTS="darwin moebius audron vorador"

case "${UNAME_S}" in
"Darwin")
    _HOST="darwin"
    ;;
*)
    _HOST=$(cat /etc/hostname)
    ;;
esac

if [[ ! "${ALLOWED_HOSTS}" =~ ${_HOST} ]]; then
    echo "ERROR: Host \"${_HOST}\" not supported."
    exit 1
fi

ROLES=""
REPOS=()
COLOURS="gruvbox-material"

case "${_HOST}" in
"darwin")
    ROLES="desktop code"
    REPOS+=("git@github.com:tbreslein/ringheap.rs.git")
    ;;
"moebius")
    ROLES="linux desktop wayland code gaming"
    REPOS+=("git@github.com:tbreslein/capturedlambdav2.git")
    REPOS+=("git@github.com:tbreslein/devl.git")
    REPOS+=("git@github.com:tbreslein/shyr.git")
    REPOS+=("git@github.com:tbreslein/ringheap.rs.git")
    ;;
"audron")
    ROLES="linux desktop wayland code laptop"
    REPOS+=("git@github.com:tbreslein/capturedlambdav2.git")
    REPOS+=("git@github.com:tbreslein/devl.git")
    REPOS+=("git@github.com:tbreslein/shyr.git")
    REPOS+=("git@github.com:tbreslein/ringheap.rs.git")
    ;;
"vorador")
    ROLES="linux rbpi"
    ;;
esac

X11_WM="awesome"
WAYLAND_WM="hyprland"

REPOS_STRING=$(
    IFS=" "
    echo "${REPOS[*]}"
)

{
    echo "UNAME_S=\"${UNAME_S}\""
    echo "_HOST=\"${_HOST}\""
    echo "ROLES=\"${ROLES}\""
    echo "X11_WM=\"${X11_WM}\""
    echo "WAYLAND_WM=\"${WAYLAND_WM}\""
    echo "COLOURS=\"${COLOURS}\""
    echo "REPOS=\"${REPOS_STRING}\""
} >"${SCRIPT_DIR}/.env"
