---
- name: Enable fstrim.service
  ansible.builtin.service:
    name: fstrim.service
    state: started
    enabled: true

- name: Stow dotfiles
  become_user: tommy
  ansible.builtin.shell:
    cmd: "stow -d $HOME/dots/config -t ~/ {{ item }}"
  loop: "{{ common_stows }}"

- name: Link scripts
  ansible.builtin.file:
    src: "/home/tommy/dots/scripts/{{ item }}"
    dest: "/home/tommy/.local/bin/{{ item }}"
    owner: tommy
    state: link
  loop: "{{ scripts }}"

- name: Install Arch repo packages
  ansible.builtin.pacman:
    name: "{{ item }}"
    state: present
  loop: "{{ arch_packages }}"

- name: Install AUR packages
  become: true
  become_user: kain
  kewlfft.aur.aur:
    name: "{{ item }}"
  loop: "{{ aur_packages }}"
