#!/usr/bin/env zsh

. "$HOME/.config/zsh/.zshrc"

pushd "$HOME/dots"
git pull || exit 1
popd

zap update
{ sudo -i -u kain paru } && \
rustup update && \
zvm i master && \
nvim -c 'lua require("lazy").sync()'
# pushd "$HOME/Downloads/zls/" && git pull && zig build -Doptimize=ReleaseSafe -p ~/.local/ && popd &&
