#!/usr/bin/env zsh

. "$HOME/.config/zsh/.zshrc"

pushd "$HOME/dots"
git pull || exit 1
popd

zap update
sudo dnf update && \
npm update -g && \
rustup self update && \
rustup update && \
nvim --headless -c 'autocmd User MasonUpdateAllComplete quitall' -c 'MasonUpdateAll' && \
nvim -c 'lua require("lazy").sync()'
