---
dnf_packages:
  # terminal
  - alacritty
  - neovim
  - vim
  - htop
  - rsync
  - zsh
  - udisks2
  - stow
  - ripgrep
  - fzf
  - fd-find
  - exa
  - starship
  - lazygit
  - bottom
  - neofetch
  - bat
  - zoxide
  - grim

  # coding
  - g++
  - cmake
  - llvm
  - nodejs

  # deps
  - libgit2-devel
  - libcurl-devel
  - libssh2-devel
  - openssl-devel
  - pkg-config

  # gui
  - brave-browser
  - thunderbird

  # desktop/system
  - dunst
  - gnome-tweaks
  - gnome-extensions-app
  - hack-fonts
  - kanshi
  - network-manager-applet
  - NetworkManager-fortisslvpn
  - swappy
  - waybar
  - wdisplays
  - wlsunset
  - wofi
  - xdg-desktop-portal
  - xdg-desktop-portal-wlr
  - sway
  - hyprland

npm_packages:
  - prettier

flatpak_packages:
  - us.zoom.Zoom

flatpak_repos:
  - name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

yum_repos:
  - name: brave-browser
    description: Brave Browser
    baseurl: https://brave-browser-rpm-release.s3.brave.com/$basearch
    enabled: true
    gpgcakey: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

copr_repos:
  - name: zawertun/hack-fonts
    state: enabled
  - name: atim/bottom
    state: enabled
  - name: atim/lazygit
    state: enabled
  - name: atim/starship
    state: enabled
  - name: atim/zoxide
    state: enabled
  - name: kasion/Hyprland-git
    state: enabled

common_stows:
  - alacritty
  - bash
  - dunst
  - hypr
  - npm
  - nvim
  - starship
  - sway
  - swappy
  - waybar
  - zsh

users:
  - name: tommy
    full_name: Tommy Breslein
    groups: tommy,wheel
