---
dnf_packages:
  # terminal
  - alacritty
  - neovim
  - vim
  - htop
  - rsync
  - zsh
  - udisks2
  - stow
  - ripgrep

  # coding
  - g++
  - nodejs

  # gui
  - thunderbird
  - brave-browser

  # desktop/system
  - gnome-tweaks
  - gnome-extensions-app
  - sway
  - wofi
  - waybar
  - dnf-plugins-core

yum_repos:
  - name: brave-browser
    description: Brave Browser
    baseurl: https://brave-browser-rpm-release.s3.brave.com/$basearch
    enabled: true
    gpgcakey: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

common_stows:
  - alacritty
  - bash
  - nvim
  - sway
  - waybar
  - zsh
    
users:
  - name: tommy
    full_name: Tommy Breslein
    groups: tommy,wheel
