---
dnf_packages:
  # terminal
  - alacritty
  - neovim
  - vim
  - htop
  - rsync
  - zsh
  - udisks2
  - stow
  - ripgrep
  - fzf
  - fd-find
  - exa
  - starship
  - lazygit

  # coding
  - g++
  - llvm
  - nodejs

  # gui
  - thunderbird
  - brave-browser

  # desktop/system
  - gnome-tweaks
  - gnome-extensions-app
  - sway
  - wofi
  - waybar
  - hack-fonts

npm_packages:
  - prettier

yum_repos:
  - name: brave-browser
    description: Brave Browser
    baseurl: https://brave-browser-rpm-release.s3.brave.com/$basearch
    enabled: true
    gpgcakey: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

copr_repos:
  - name: zawertun/hack-fonts
    state: enabled
  - name: atim/lazygit
    state: enabled
  - name: atim/starship
    state: enabled

common_stows:
  - alacritty
  - bash
  - npm
  - nvim
  - sway
  - waybar
  - zsh
    
users:
  - name: tommy
    full_name: Tommy Breslein
    groups: tommy,wheel
