---
- name: Install Arch repo packages
  ansible.builtin.pacman:
    name: "{{ item }}"
    state: present
  loop: "{{ arch_packages }}"

- name: Install AUR packages
  become: true
  become_user: kain
  kewlfft.aur.aur:
    name: "{{ item }}"
  loop: "{{ aur_packages }}"

- name: Setup .npm_global
  ansible.builtin.file:
    dest: "~/.npm_global"
    owner: tommy
    state: directory

- name: init opam
  become: true
  become_user: tommy
  ansible.builtin.shell: opam init -a

- name: install opam packages
  become: true
  become_user: tommy
  ansible.builtin.shell: opam install "{{ item }}" -y
  loop: "{{ opam_packages}}"

- name: Check if cargo is installed
  become_user: tommy
  stat: path=~/.cargo/bin/cargo
  register: cargo_bin
  ignore_errors: true

- name: Download rustup installer
  become_user: tommy
  when: not cargo_bin.stat.exists
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: 0755
    force: true

- name: Install rust/cargo
  become_user: tommy
  when: not cargo_bin.stat.exists
  ansible.builtin.shell: /tmp/sh.rustup.rs -y

- name: Install rustup components
  become_user: tommy
  when: not cargo_bin.stat.exists
  ansible.builtin.shell: |
    rustup default stable
    rustup component add rustfmt rust-analyzer clippy rust-src llvm-tools rust-docs rust-std
    rustup toolchain install nightly --component rustfmt rust-analyzer clippy rust-src llvm-tools rust-docs rust-std
