---
- name: Install dnf plugins
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: present
      
- name: Add additional yum repositories
  ansible.builtin.yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    enabled: "{{ item.enabled }}"
    gpgcakey: "{{ item.gpgcakey }}"
  loop: "{{ yum_repos }}"

- name: Add copr repositories
  community.general.copr:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ copr_repos }}"

- name: Update dnf cache
  ansible.builtin.dnf:
    name: vim
    update_cache: true
    state: present

- name: Install dnf packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ dnf_packages }}"

- name: Create users
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.full_name }}"
    create_home: true
    shell: /bin/zsh
    state: present
    groups: "{{ item.groups }}"
    append: true
  loop: "{{ users }}"

- name: Stow dotfiles
  become_user: tommy
  ansible.builtin.shell:
    cmd: "stow -d $HOME/dots/config -t ~/ {{ item }}"
  loop: "{{ common_stows }}"

- name: Setup .npm_global
  ansible.builtin.file:
    dest: "~/.npm_global"
    owner: tommy
    state: directory
      #register: sshdir

- name: Install global npm packages
  become_user: tommy
  community.general.npm:
    name: "{{ item }}"
    global: true
    state: present
  loop: "{{ npm_packages }}"
